* Соударение
** Как у нас
   Считаем время до соударения с плоскостью. Если оно положительная,
   то точка ещё не долетела. Если отрицательное, то перелёт — нужно
   вернуть точку в место столкновения и вместо отлёта внутрь за
   плоскость вернуть её наружу, обратив вдоль нормали вектор скорости.
*** Композиции
    *Пересечение*: вычисляем время до удара с каждой поверхностью. Если
    они все отрицательные (пролетели внутрь *каждой*), вычисляем из
    них минимальное, для соответствующей поверхности делаем отскок и
    обращаем скорость от неё.
** Bird
** Закиров
   Строим пересечение луча и кривой второго порядка, получая две точки
   t (время соударения). Если t ≥ eps (отсечка отрицательных корней),
   то был удар. Закиров не учитывает соударения частиц до подлёта к
   телу, поэтому можно сразу построить прямую и найти для неё точку
   удара. В таком подходе нет итерирования по времени вообще, точки
   как бы сразу долетают до тела.
** Как ускорить и улучшить
   - для тел вводить упрощённый описывающий объём и сначала проверять,
     попала ли точка в него;
   - разбивать пространство через octree;
   - разбивать пространство на адаптивную сетку (также полезно для
     соударений) и проверять на удары только с поверхностями,
     попавшими в ячейку сетки
